services:
  postgres:
    image: postgres:15-alpine
    container_name: usuarios_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua_senha_aqui
      POSTGRES_DB: usuarios_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
